name: api.typo3.org

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        core: ['main', '12.4', '11.5']
    env:
      TARGET_PATH: ${{ secrets.API_TARGET_PATH }}/${{ matrix.core }}
    steps:
      - name: Checkout Doxygen API
        uses: actions/checkout@v4
        with:
          repository: 'TYPO3-Documentation/t3docs-typo3-api'
          fetch-depth: 0
          path: .phpdoc

      - name: Checkout Core ${{ matrix.core }}
        uses: actions/checkout@v4
        with:
          repository: 'typo3/typo3'
          path: .Build/TYPO3
          ref: ${{ matrix.core }}

      - name: copy config
        run: cp .phpdoc/phpdoc.dist.xml phpdoc.xml

      - name: Generate API Docs
        run: |
          mkdir -p output/${{ matrix.core }}
          docker run --rm \
            -v $(pwd)/data:/data \
            phpdoc/phpdoc:3 --target output/${{ matrix.core }}

      - name: SCP files to production system
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_DOCS_API_HOST }}
          username: ${{ secrets.DEPLOY_DOCS_API_USERNAME }}
          key: ${{ secrets.DEPLOY_DOCS_API_KEY }}
          source: "output/${{ matrix.core }}"
          rm: false
          strip_components: 2
          tar_tmp_path: ${{ secrets.API_TMP_TARGET_PATH }}
          target: ${{ env.TARGET_PATH }}
