name: api.typo3.org

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        core: ['master', '10.4', '9.5']
    env:
      TARGET_PATH: ${{ secrets.API_TARGET_PATH }}/${{ matrix.core }}
    steps:
      - name: Checkout Doxygen API
        uses: actions/checkout@v2
        with:
          repository: 'TYPO3GmbH/doxygenapi'
          fetch-depth: 0
          path: api

      - name: Checkout Core ${{ matrix.core }}
        uses: actions/checkout@v2
        with:
          repository: 'typo3/typo3'
          path: core
          ref: ${{ matrix.core }}

      - name: Generate API Docs
        run: |
          echo -e "\nPROJECT_NAME           = TYPO3 CMS" >> api/Doxyfile
          echo -e "\nPROJECT_NUMBER         = ${{ matrix.core }}" >> api/Doxyfile
          mkdir -p output/${{ matrix.core }}
          docker run --rm --user=$(id -u):$(id -g) \
            -v $(pwd)/core:/mnt/doxygen:ro \
            -v $(pwd)/api:/mnt/doxyconf \
            -v $(pwd)/output/${{ matrix.core }}:/mnt/output \
            ghcr.io/typo3gmbh/doxygenapi /mnt/doxyconf/Doxyfile

      - name: SCP files to production system
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_DOCS_API_HOST }}
          username: ${{ secrets.DEPLOY_DOCS_API_USERNAME }}
          key: ${{ secrets.DEPLOY_DOCS_API_KEY }}
          source: "output/${{ matrix.core }}/html/"
          rm: false
          strip_components: 3
          tar_tmp_path: ${{ secrets.API_TMP_TARGET_PATH }}
          target: ${{ env.TARGET_PATH }}
