name: Fluid ViewHelper Documentation

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        core: ['main', '13.4', '12.4']
      fail-fast: false
    env:
      TARGET_PATH: ${{ secrets.API_TARGET_PATH }}/${{ matrix.core }}
    steps:

      - name: Setup PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create RST documentation for Core ${{ matrix.core }}
        working-directory: ./Build/fluid-viewhelpers/${{ matrix.core }}
        run: |
          composer install --no-dev -n -o --no-progress
          composer generate-documentation
          cp -r fluidDocumentationOutput ../../../documentation

      - name: "Checkout ViewHelper Docs: ${{ matrix.core }}"
        uses: actions/checkout@v4
        with:
          repository: 'TYPO3-Documentation/TYPO3CMS-Reference-ViewHelper'
          path: viewhelpers
          ref: ${{ matrix.core }}
          token: ${{ secrets.GH_PUSH_TOKEN }}

      - name: Update repository
        working-directory: ./viewhelpers
        continue-on-error: true
        run: |
          for file in ../documentation/*; do
            target_file="Documentation/$(basename "$file")"
            if [ ! -f "$target_file" ]; then
              cp -r "$file" Documentation/
            fi
          done
          git checkout HEAD -- Documentation/Index.rst
          git config user.name "TYPO3 Documentation Team"
          git config user.email "documentation-automation@typo3.com"
          git add .
          git commit -m '[BOT][TASK] Automatic Update of ViewHelper reference' || echo "No changes to commit"
          git push
