name: Fluid ViewHelper Documentation

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        core: ['main', '12.4']
      fail-fast: false
    env:
      TARGET_PATH: ${{ secrets.API_TARGET_PATH }}/${{ matrix.core }}
    steps:

      - name: Setup PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Checkout Core ${{ matrix.core }}
        uses: actions/checkout@v2
        with:
          repository: 'typo3/typo3'
          path: core
          ref: ${{ matrix.core }}

      - name: Create RST documentation
        working-directory: ./core
        run: |
          composer install --no-dev -n -o --no-progress
          composer req t3docs/fluid-documentation-generator
          vendor/bin/fluidDocumentation generate vendor/t3docs/fluid-documentation-generator/config/typo3/*
          cp -r fluidDocumentationOutput ../documentation

      - name: "Checkout ViewHelper Docs: ${{ matrix.core }}"
        uses: actions/checkout@v2
        with:
          repository: 'TYPO3-Documentation/TYPO3CMS-Reference-ViewHelper'
          path: viewhelpers
          ref: ${{ matrix.core }}
          token: ${{ secrets.GH_PUSH_TOKEN }}

      - name: Update repository
        working-directory: ./viewhelpers
        # - fails if there are no changes
        # - keep original Documentation/Index.rst
        continue-on-error: true
        run: |
          cp -rf ../documentation/* Documentation/
          git checkout HEAD -- Documentation/Index.rst
          git config user.name "TYPO3 Documentation Team"
          git config user.email "documentation-automation@typo3.com"
          git add .
          git commit -m '[BOT][TASK] Automatic Update of ViewHelper reference'
          git push
