name: Main Rendering
on:
  repository_dispatch:
    types: [ 'render' ]

jobs:
  render:
    runs-on: ubuntu-latest
    name: Render ${{ github.event.client_payload.vendor }}/${{ github.event.client_payload.name }}
    if: ${{ github.event.client_payload.repository_url != '' && github.event.client_payload.source_branch != '' && github.event.client_payload.target_branch_directory != '' }}
    steps:
      - name: Notify on start
        if: ${{ always() }}
        uses: distributhor/workflow-webhook@2381f0e9c7b6bf061fb1405bd0804b8706116369
        env:
          webhook_url: ${{ secrets.WEBHOOK_START_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          data: '{"success":false,"id":"${{ github.event.client_payload.id }}","link":"https://github.com/TYPO3-Documentation/t3docs-ci-deploy/actions/runs/${{ github.run_id }}"}'

      - name: Checkout project repository
        shell: bash
        run: |
          git clone --depth 1 ${{ github.event.client_payload.repository_url }} -b ${{ github.event.client_payload.source_branch }} ${{ github.workspace }}/t3docsproject

      - id: enable_guides
        working-directory: ${{ github.workspace }}/t3docsproject
        shell: bash
        run: |
          if [[ -f Documentation/settings.cfg && ! -f Documentation/guides.xml ]]; then
            echo "MIGRATED=false" >> $GITHUB_OUTPUT
          else
            echo "MIGRATED=true" >> $GITHUB_OUTPUT
          fi

      - id: pre-render-guides
        working-directory: ${{ github.workspace }}/t3docsproject
        shell: bash
        run: mkdir -p RenderedDocumentation/Result/project/0.0.0

      - id: migrate
        if: steps.enable_guides.outputs.MIGRATED == 'false' && hashFiles('Documentation/settings.cfg') != ''
        shell: bash
        working-directory: ${{ github.workspace }}/t3docsproject
        run: |
          echo "::warning file=Documentation/settings.cfg,line=1,title=Please migrate::Forced migration activated. Your project is not yet using the PHP-based rendering, please properly migrate: https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/Howto/Migration/Index.html"
          
          # Run migration, but do not exit on failure
          if ! docker run --rm --user=$(id -u):$(id -g) \
            --pull always \
            -v $(pwd):/project \
            ghcr.io/typo3-documentation/render-guides:latest \
              migrate Documentation; then
            echo "::warning::Migration failed, but continuing with the workflow..."
          fi

      - uses: TYPO3-Documentation/render-guides@main
        id: render-guides
        with:
          working-directory: ${{ github.workspace }}/t3docsproject
          config: ${{ github.workspace }}/t3docsproject/Documentation/
          output: ./RenderedDocumentation/Result/project/0.0.0
          configure-branch: ${{ env.source_branch }}
          configure-project-release: ${{ env.target_branch_directory }}
          configure-project-version: ${{ env.target_branch_directory }}

      - id: render-guides-localization
        shell: bash
        working-directory: ${{ github.workspace }}/t3docsproject
        run: |
          echo "::group::Prepare move of possible localizations by render-guides"
          
          # "render-guides" uses a different directory structure than sphinx did.
          # Sphinx puts localizations OUTSIDE the main 0.0.0 directory tree, using "xx-yy"
          # render-guides puts localizations WITHIN the main 0.0.0 directory tree, and
          #               uses "Localization.xx_YY" directory names
          
          # This step harmonizes that to the expected sphinx directory structure.
          
          # Expected directory structure BEFORE:
          # RenderedDocumentation/Result/project/0.0.0/Index.html
          # RenderedDocumentation/Result/project/0.0.0/Sub/Index.html
          # RenderedDocumentation/Result/project/0.0.0/Localization.de_DE/Index.html
          # RenderedDocumentation/Result/project/0.0.0/Localization.de_DE/Sub/Index.html
          # RenderedDocumentation/Result/project/0.0.0/Localization.ru_RU/Index.html
          # RenderedDocumentation/Result/project/0.0.0/Localization.ru_RU/Sub/Index.html

          # Expected directory structure AFTER:
          # RenderedDocumentation/Result/project/0.0.0/Index.html
          # RenderedDocumentation/Result/project/0.0.0/Sub/Index.html
          # RenderedDocumentation/Result/project/de-de/0.0.0/Index.html
          # RenderedDocumentation/Result/project/de-de/0.0.0/Sub/Index.html
          # RenderedDocumentation/Result/project/ru-ru/0.0.0/Index.html
          # RenderedDocumentation/Result/project/ru-ru/0.0.0/Sub/Index.html

          projectBaseDirectory="RenderedDocumentation/Result/project/0.0.0/"
          if [ -d $projectBaseDirectory ]; then
                  currentWorkingDir=$(pwd)
                  cd $projectBaseDirectory
                  for localizationDirectory in Localization.*; do
                          echo "$localizationDirectory check..."
                          if [[ -d $localizationDirectory ]]; then
                                  sub_dir_name=$(echo "$localizationDirectory" | sed 's/Localization.//' | tr '[:upper:]' '[:lower:]' | tr '_' '-')
                                  echo "  Operating on $sub_dir_name"
                                  # Check if the subdirectory name matches the required pattern
                                  if [[ $sub_dir_name =~ ^[a-z]+-[a-z]+$ ]]; then
                                          # Move something like:
                                          # > RenderedDocumentation/Result/project/0.0.0/Localization.ru_RU/
                                          # to
                                          # > RenderedDocumentation/Result/project/ru_RU/0.0.0
                                          # This will allow further processing in the next steps.
                                          echo "    Move $localizationDirectory to ../$sub_dir_name/0.0.0"
                                          mkdir -p "../$sub_dir_name"
                                          mv "$localizationDirectory" "../$sub_dir_name/0.0.0"
                                  else
                                          echo "    Invalid localization."
                                  fi
                          else
                              echo "  Not a directory."
                          fi
                  done
                  cd $currentWorkingDir
          fi
          echo "::endgroup::"

      - id: langhandling
        shell: bash
        working-directory: ${{ github.workspace }}/t3docsproject
        run: |
          echo "::group::Prepare final structure"

          # Expected directory structure BEFORE:
          # RenderedDocumentation/Result/project/0.0.0/Index.html
          # RenderedDocumentation/Result/project/0.0.0/Sub/Index.html
          # RenderedDocumentation/Result/project/de-de/0.0.0/Index.html
          # RenderedDocumentation/Result/project/de-de/0.0.0/Sub/Index.html
          # RenderedDocumentation/Result/project/ru-ru/0.0.0/Index.html
          # RenderedDocumentation/Result/project/ru-ru/0.0.0/Sub/Index.html

          # Expected directory structure AFTER:
          # FinalDocumentation/en-us/Index.html
          # FinalDocumentation/en-us/Sub/Index.html
          # FinalDocumentation/de-de/Index.html
          # FinalDocumentation/de-de/Sub/Index.html
          # FinalDocumentation/ru-ru/Index.html
          # FinalDocumentation/ru-ru/Sub/Index.html

          # if a result has been rendered for the main directory, we treat that as the 'en_us' version
          if [ -d RenderedDocumentation/Result/project/0.0.0/ ]; then
                  echo "Handling main doc result as en-us version"
                  mkdir -p FinalDocumentation/en-us
                  # Move en-us files to target dir, including dot files
                  (shopt -s dotglob; mv RenderedDocumentation/Result/project/0.0.0/* FinalDocumentation/en-us)
                  # Remove the directory, all content has been moved
                  rmdir RenderedDocumentation/Result/project/0.0.0/
                  # Remove a possibly existing Localization.en_us directory, if it exists
                  rm -rf RenderedDocumentation/Result/project/en-us/
          fi

          # now see if other localization versions have been rendered. if so, move them to FinalDocumentation/, too
          if [ "$(ls -A RenderedDocumentation/Result/project/)" ]; then
              for LOCALIZATIONDIR in RenderedDocumentation/Result/project/*; do
                      LOCALIZATION=`basename $LOCALIZATIONDIR`
                      echo "Handling localized documentation version ${LOCALIZATION:?Localization could not be determined}"
                      mkdir FinalDocumentation/${LOCALIZATION}
                      (shopt -s dotglob; mv ${LOCALIZATIONDIR}/0.0.0/* FinalDocumentation/${LOCALIZATION})
                      # Remove the localization dir, it should be empty now
                      rmdir ${LOCALIZATIONDIR}/0.0.0/
                      rmdir ${LOCALIZATIONDIR}
              done
          fi
          echo "::endgroup::"

      - name: Publish archive with result
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
        with:
          name: result
          path: ${{ github.workspace }}/t3docsproject/FinalDocumentation/
          if-no-files-found: error

      - name: Notify on failure
        if: ${{ failure() }}
        uses: distributhor/workflow-webhook@2381f0e9c7b6bf061fb1405bd0804b8706116369
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          data: '{"success":false,"id":"${{ github.event.client_payload.id }}","link":"https://github.com/TYPO3-Documentation/t3docs-ci-deploy/actions/runs/${{ github.run_id }}"}'

  deploy:
    runs-on: ubuntu-latest
    name: Deploy ${{ github.event.client_payload.vendor }}/${{ github.event.client_payload.name }}
    needs: render
    if: ${{ github.event.client_payload.type_short != '' && github.event.client_payload.vendor != '' && github.event.client_payload.name != '' && github.event.client_payload.target_branch_directory != ''}}
    steps:
      - uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3
        with:
          name: result

      - name: Extract render result
        run: unzip rendered-docs.zip -d result

      - name: Adjust permissions
        run: chmod -R go+rX result

      - name: Fallback to README-like file if Index.html is missing
        run: |
          fallback=$(find result -type f -iname "readme.html" | head -n 1)
          if [ -n "$fallback" ]; then
            fallback_dir=$(dirname "$fallback")
            if [ ! -f "$fallback_dir/Index.html" ]; then
              cp "$fallback" "$fallback_dir/Index.html"
            fi
          fi

      - name: Insert redirecting Index.html in folders missing one
        shell: bash
        run: |
          find result \( -path "*/_sources" -o -path "*/_sources/*" -o -path "*/_resources" -o -path "*/_resources/*" \) -prune -o -type d -print | while read dir; do
            if [ ! -f "$dir/Index.html" ]; then
              echo "Creating Index.html in $dir"
              echo '<!DOCTYPE html>' > "$dir/Index.html"
              echo '<html>' >> "$dir/Index.html"
              echo '  <head>' >> "$dir/Index.html"
              echo '    <meta http-equiv="refresh" content="0; url=../Index.html">' >> "$dir/Index.html"
              echo '  </head>' >> "$dir/Index.html"
              echo '  <body>' >> "$dir/Index.html"
              echo '    <p>If you are not redirected, <a href="../Index.html">click here</a>.</p>' >> "$dir/Index.html"
              echo '  </body>' >> "$dir/Index.html"
              echo '</html>' >> "$dir/Index.html"
            fi
          done


      - name: Upload Documentation
        uses: appleboy/scp-action@ff85246acaad7bdce478db94a363cd2bf7c90345
        with:
          host: ${{ secrets.DEPLOY_DOCS_HOST }}
          username: ${{ secrets.DEPLOY_DOCS_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "result/"
          rm: true
          strip_components: 1
          tar_tmp_path: ${{ secrets.TMP_TARGET_PATH }}
          target: ${{ secrets.TARGET_PATH }}/${{ github.event.client_payload.type_short }}/${{ github.event.client_payload.vendor }}/${{ github.event.client_payload.name }}/${{ github.event.client_payload.target_branch_directory }}

      - name: Update Extension list
        uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2
        with:
          host: ${{ secrets.DEPLOY_DOCS_HOST }}
          username: ${{ secrets.DEPLOY_DOCS_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: curl https://intercept.typo3.com/assets/docs/extensions.js --output ${{ secrets.TARGET_PATH }}/Home/extensions.js

      - name: Update search data
        uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2
        with:
          host: ${{ secrets.DEPLOY_DOCS_HOST }}
          username: ${{ secrets.DEPLOY_DOCS_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          command_timeout: 20m
          script: |
            export APP_ENV=prod
            export APP_SECRET=${{ secrets.DOC_SEARCH_APP_SECRET }}
            export DOCS_ROOT_PATH=${{ secrets.TARGET_PATH }}
            cd ${{ secrets.DOC_SEARCH_PATH }}
            ./bin/console docsearch:import ${{ github.event.client_payload.type_short }}/${{ github.event.client_payload.vendor }}/${{ github.event.client_payload.name }}/${{ github.event.client_payload.target_branch_directory }}

      - name: Notify on failure
        if: ${{ failure() }}
        uses: distributhor/workflow-webhook@2381f0e9c7b6bf061fb1405bd0804b8706116369
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          data: '{"success":false,"id":"${{ github.event.client_payload.id }}","link":"https://github.com/TYPO3-Documentation/t3docs-ci-deploy/actions/runs/${{ github.run_id }}"}'

      - name: Notify on success
        if: ${{ success() }}
        uses: distributhor/workflow-webhook@2381f0e9c7b6bf061fb1405bd0804b8706116369
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          data: '{"success":true,"id":"${{ github.event.client_payload.id }}","link":"https://github.com/TYPO3-Documentation/t3docs-ci-deploy/actions/runs/${{ github.run_id }}"}'
