name: Documentation Rendering
on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version'
        type: string
        default: '3.12'

jobs:
  render:
    permissions:
      contents: read
    name: Render Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "${{ inputs.python-version }}"

      - name: Render documentation
        run: |
          if [ -f "composer.json" ] && grep -q "typo3/guides-cli" composer.json; then
            composer install --no-interaction --no-progress --prefer-dist
            vendor/bin/guides --no-progress Documentation
          else
            pip install typo3-docs-theme
            typo3-docs-theme render Documentation
          fi
